### ISSUE TITLE
Tasks List for Libtiff pipeline

### ISSUE THREAD

**Issue by saurabhpujar** [AICoE/Varangian#24]
Milestone 2: Implement the AugSA inference pipeline on Libtiff (https://gitlab.com/libtiff/libtiff)

- [ ] Bot
    - [x] Improve Issue Features
        - [x] #17 Hide the id
        - [x] #17 Infer bug type should link to it's definition
        - [x] #21 Link to ranking explanation
        - [x] #21 Link to confidence explanation
        - [x] #17 Link to issue on Varangian repo to get developer feed back
    - [x] #17 Implement bot on Libtiff fork
    - [ ] Implement bot on Libtiff main branch
- [x] Inference Pipeline
    - [x] Run inference pipeline on latest commit
    - [x] Verify output
    - [x] Move all the inference code to https://github.com/rh-ibm-synergy (https://github.com/rh-ibm-synergy/fp_reduction, https://ibm.box.com/s/wzrtb9ew8udf3z56uuz479o2mhj7ua5x)
- [x] Last steps
    - [x] #26
