### ISSUE TITLE
OKR and Tasks for Inference Scale Out (Milestone 3)

### ISSUE THREAD

**Issue by saurabhpujar** [AICoE/Varangian#29]
Milestone 3
Period: October to December 2021

OKRs
- [ ] **Objective:** Scale Varangian to new OS projects 
    - [ ] **Key Result:** We have 6 repos by Jan 2022
    - [ ] Tasks:
        - [ ] Generate D2A V2 training data for 6 repos
        - [ ] Train models for the 6 repos
        - [ ] Automate D2A Retraining
        - [ ] Containerize and auto-start inference pipeline
        - [ ] Automate the training pipeline
        - [ ] Containerize and auto-start training pipeline. 
- [ ] **Objective:** Scale models to repos with less data
    - [ ] **Key Result:** Improve Model Performance on cross project datasets
    - [ ] Tasks:
        - [ ] #30 Generate Ensemble baselines
        - [ ] #30 Generate C-BERT baselines
        - [ ] Improve ensemble performance: 
            - [ ] #31 Feature Engineering
            - [ ] Separability, Segmentation
        - [ ] Improve C-BERT performance: More data, better model
- [ ] **Objective:** Add features for better user engagement 
    - [ ] **Key Result:** Bot will have 5 new features
    - [ ] Tasks:
        - [ ] Tag/Assign users to issue
        - [ ] Access to full ranked list, traces
        - [ ] Issue management
            - [ ] Close resolved open issues
            - [ ] Issues marked FP are not opened again
            - [ ] Issues marked FP are reviewed
            - [ ] Duplicate issues are not opened
            - [ ] Resolved Issue Feedback to backend 
        - [ ] Aggregate issues
